"""adicionando categria_id a tabela loja

Revision ID: 3188288d36c8
Revises: 
Create Date: 2025-03-11 14:50:04.970849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3188288d36c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_endereco_loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=50), nullable=False))

    with op.batch_alter_table('tb_lojas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tb_categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_lojas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('tb_endereco_loja', schema=None) as batch_op:
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
